config/routes.rb
Rails.application.routes.draw do
  resources :people

  resources :schools

  resources :life_events

  root 'home#index'

end

app/models/life_event.rb
class LifeEvent < ActiveRecord::Base
  validates :title, :date, presence: true
  validates :description, presence: true, length: { maximum: 140 }
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, presence: true
  has_many :life_events
  has_many :schools
end

app/models/school.rb
class School < ActiveRecord::Base
  validates :school_name, presence: true
  validates :beginning_year, presence: true
  validates :ending_year, presence: true
  validates :beginning_year, numericality: { less_than_or_equal_to: :ending_year }
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @schools = School.all
    @life_events = LifeEvent.all
    @people = Person.all
  end
  
end

app/controllers/life_events_controller.rb
class LifeEventsController < ApplicationController
  before_action :set_life_event, only: [:show, :edit, :update, :destroy]

  # GET /life_events
  # GET /life_events.json
  def index
    @life_events = LifeEvent.all
  end

  # GET /life_events/1
  # GET /life_events/1.json
  def show
  end

  # GET /life_events/new
  def new
    @life_event = LifeEvent.new
  end

  # GET /life_events/1/edit
  def edit
  end

  # POST /life_events
  # POST /life_events.json
  def create
    @life_event = LifeEvent.new(life_event_params)

    respond_to do |format|
      if @life_event.save
        format.html { redirect_to @life_event, notice: 'Life event was successfully created.' }
        format.json { render :show, status: :created, location: @life_event }
      else
        format.html { render :new }
        format.json { render json: @life_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /life_events/1
  # PATCH/PUT /life_events/1.json
  def update
    respond_to do |format|
      if @life_event.update(life_event_params)
        format.html { redirect_to @life_event, notice: 'Life event was successfully updated.' }
        format.json { render :show, status: :ok, location: @life_event }
      else
        format.html { render :edit }
        format.json { render json: @life_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /life_events/1
  # DELETE /life_events/1.json
  def destroy
    @life_event.destroy
    respond_to do |format|
      format.html { redirect_to life_events_url, notice: 'Life event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_life_event
      @life_event = LifeEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def life_event_params
      params.require(:life_event).permit(:title, :date, :description, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:school_name, :beginning_year, :ending_year, :city, :state, :country, :person_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/life_events_helper.rb
module LifeEventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/home/index.html.erb
<div class='row'>
  <div class='columns large-12 text-center'>
    <h1>Welcome to Life Tracker!</h1>
  </div>
</div>

<div class='row'>
  <div class='columns large-6'>
    <h2>Recent Schools</h2>
    <% @schools.order(:created_at).limit(5).each do |school| %>
        <p><%= school.person.name %> just added <%= school.school_name %> to his list of schools!</p>
        <p><%= school.created_at %></p>
    <% end %>
  </div>

  <div class='columns large-6'>
    <h2>Recent Life Events</h2>
    <% @life_events.order(:created_at).limit(5).each do |event| %>
        <p><%= event.person.name %> just added <%= event.title %> to his list of schools!</p>
        <p><%= event.created_at %></p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

    <header>
      <nav class='top-bar' data-topbar>
        <ul class='title-area'>
          <li class='name'>
            <h1><%= link_to  'Home', "/" %></h1>
          </li>
        </ul>

        <section class='top-bar-section'>
          <ul class='left'>
            <li><%= link_to 'Schools', schools_path%></li>
            <li><%= link_to 'Life Events', life_events_path%></li>
            <li><%= link_to 'People', people_path%></li>
          </ul>
        </section>
      </nav>
    </header>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/life_events/_form.html.erb
<%= form_for(@life_event) do |f| %>
  <% if @life_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@life_event.errors.count, "error") %> prohibited this life_event from being saved:</h2>

      <ul>
      <% @life_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id, "Person" %><br>
    <%= f.collection_select :person_id, Person.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/life_events/edit.html.erb
<h1>Editing life_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @life_event %> |
<%= link_to 'Back', life_events_path %>

app/views/life_events/index.html.erb
<h1>Listing Life Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Date</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @life_events.each do |life_event| %>
      <tr>
        <td><%= life_event.person.name %></td>
        <td><%= life_event.title %></td>
        <td><%= life_event.date %></td>
        <td><%= life_event.description %></td>
        <td><%= link_to 'Show', life_event %></td>
        <td><%= link_to 'Edit', edit_life_event_path(life_event) %></td>
        <td><%= link_to 'Destroy', life_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Life Event', new_life_event_path %>

app/views/life_events/new.html.erb
<h1>New life_event</h1>

<%= render 'form' %>

<%= link_to 'Back', life_events_path %>

app/views/life_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @life_event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @life_event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @life_event.description %>
</p>

<%= link_to 'Edit', edit_life_event_path(@life_event) %> |
<%= link_to 'Back', life_events_path %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <ul>
    <strong>School Name</strong>
    <% @person.schools.order(:beginning_year).each do |school| %>
      <li><%= school.school_name %></li>
    <%  end %>
  </ul>
</p>

<p>
  <ul>
    <strong>Event Title</strong>
    <% @person.life_events.order(:date).each do |life_event| %>
      <li><%= life_event.title %></li>
    <%  end %>
  </ul>
</p>



<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :person_id, "Person" %><br>
    <%= f.collection_select :person_id, Person.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :school_name %><br>
    <%= f.text_field :school_name %>
  </div>
  <div class="field">
    <%= f.label :beginning_year %><br>
    <%= f.number_field :beginning_year %>
  </div>
  <div class="field">
    <%= f.label :ending_year %><br>
    <%= f.number_field :ending_year %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>School name</th>
      <th>Beginning year</th>
      <th>Ending year</th>
      <th>City</th>
      <th>State</th>
  <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.person.name %></td>
        <td><%= school.school_name %></td>
        <td><%= school.beginning_year %></td>
        <td><%= school.ending_year %></td>
        <td><%= school.city %></td>
        <td><%= school.state %></td>
        <td><%= school.country %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School name:</strong>
  <%= @school.school_name %>
</p>

<p>
  <strong>Beginning year:</strong>
  <%= @school.beginning_year %>
</p>

<p>
  <strong>Ending year:</strong>
  <%= @school.ending_year %>
</p>

<p>
  <strong>City:</strong>
  <%= @school.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @school.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @school.country %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>